# Generated by Django 5.2 on 2025-06-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sub_category', models.CharField(max_length=100)),
                ('restock_threshold', models.IntegerField(default=10)),
            ],
        ),
    ]
